import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { supabase } from "../lib/supabase";
type Cleaner={id:string;slug:string;business_name:string|null;logo_url:string|null;address:string|null;phone:string|null;whatsapp:string|null;website:string|null;about:string|null;contact_email:string|null};
type Service={id:string;service:string;variant:string|null;price_cents:number|null};
type Site={headline:string|null;description:string|null;hero_url:string|null;primary_color:string;accent_color:string;show_services:boolean;show_about:boolean;show_contact:boolean;is_published:boolean};
const defaults:Site={headline:null,description:null,hero_url:null,primary_color:"#0f172a",accent_color:"#34d399",show_services:true,show_about:true,show_contact:true,is_published:true};
function name(s:string,v:string|null){const n=s.replace(/_/g," ").replace(/\b\w/g,l=>l.toUpperCase());return v?`${n} · ${v}`:n} function price(c:number|null){return c==null?null:new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(c/100)} function website(v:string){return /^https?:\/\//i.test(v)?v:`https://${v}`}
export default function PublicCleanerSite(){const {slug}=useParams<{slug:string}>();const [cleaner,setCleaner]=useState<Cleaner|null>(null);const [site,setSite]=useState<Site>(defaults);const [services,setServices]=useState<Service[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
useEffect(()=>{let cancelled=false;(async()=>{if(!slug){setLoading(false);return}setLoading(true);setError(null);const {data:c,error:ce}=await supabase.from("cleaners").select("id,slug,business_name,logo_url,address,phone,whatsapp,website,about,contact_email").eq("slug",slug).eq("is_published",true).eq("is_active",true).maybeSingle();if(cancelled)return;if(ce){setError(ce.message);setLoading(false);return}if(!c){setLoading(false);return}setCleaner(c as Cleaner);const [{data:s,error:se},{data:o,error:oe}]=await Promise.all([supabase.from("cleaner_sites").select("headline,description,hero_url,primary_color,accent_color,show_services,show_about,show_contact,is_published").eq("cleaner_id",c.id).maybeSingle(),supabase.from("service_offerings").select("id,service,variant,price_cents").eq("cleaner_id",c.id).eq("is_active",true).order("service").order("variant")]);if(cancelled)return;if(se||oe)setError(se?.message||oe?.message||"Could not load page");if(s)setSite({...defaults,...(s as Site)});setServices((o||[]) as Service[]);setLoading(false)})();return()=>{cancelled=true}},[slug]);
if(loading)return <div className="min-h-screen grid place-items-center bg-slate-50">Loading…</div>;if(error)return <div className="min-h-screen grid place-items-center px-6"><div className="text-center"><h1 className="text-2xl font-bold">We couldn't load this cleaner</h1><p className="mt-2 text-slate-600">{error}</p></div></div>;if(!cleaner||!site.is_published)return <div className="min-h-screen grid place-items-center px-6"><div className="text-center"><h1 className="text-3xl font-bold">Cleaner not found</h1><p className="mt-2 text-slate-600">That business page isn't public right now.</p><Link to="/" className="mt-6 inline-flex rounded-full bg-black px-5 py-3 text-white font-semibold">Back to Klean.ly</Link></div></div>;
const wa=cleaner.whatsapp?.replace(/\D/g,"");const call=cleaner.phone||cleaner.whatsapp;const intro=site.description||cleaner.about||"Professional local cleaning with simple, direct booking and friendly service.";
return <div className="min-h-screen bg-slate-50 text-slate-950"><header className="bg-white border-b"><div className="mx-auto max-w-6xl px-5 py-5 flex items-center justify-between gap-4"><div className="flex items-center gap-3">{cleaner.logo_url?<img src={cleaner.logo_url} alt="logo" className="h-12 w-12 rounded-2xl object-contain border"/>:<div className="h-12 w-12 rounded-2xl text-white grid place-items-center font-bold" style={{background:site.primary_color}}>{(cleaner.business_name||"K")[0]}</div>}<div><div className="font-bold">{cleaner.business_name}</div><div className="text-sm text-slate-500">Local cleaning services</div></div></div><span className="text-xs sm:text-sm text-slate-500">Powered by Klean.ly</span></div></header>
<main><section className="text-white bg-cover bg-center" style={{backgroundColor:site.primary_color,backgroundImage:site.hero_url?`linear-gradient(rgba(0,0,0,.55),rgba(0,0,0,.55)), url(${site.hero_url})`:undefined}}><div className="mx-auto max-w-6xl px-5 py-16 sm:py-24 grid gap-10 lg:grid-cols-[1.3fr_.7fr] lg:items-center"><div><p className="uppercase tracking-[.22em] text-xs font-semibold mb-4" style={{color:site.accent_color}}>Trusted local cleaner</p><h1 className="text-4xl sm:text-6xl font-black tracking-tight leading-tight">{site.headline||cleaner.business_name}</h1><p className="mt-6 text-lg sm:text-xl text-white/75 max-w-2xl">{intro}</p>{site.show_contact&&<div className="mt-8 flex flex-wrap gap-3">{wa&&<a href={`https://wa.me/${wa}`} className="rounded-full px-6 py-3 font-bold" style={{background:site.accent_color,color:site.primary_color}}>Book on WhatsApp</a>}{call&&<a href={`tel:${call}`} className="rounded-full border border-white/30 px-6 py-3 font-semibold">Call now</a>}</div>}</div><div className="rounded-3xl bg-white/10 border border-white/10 p-6 backdrop-blur"><div className="text-sm text-white/65">Serving customers around</div><div className="mt-2 text-2xl font-bold">{cleaner.address||"your local area"}</div></div></div></section>
{site.show_services&&<section className="mx-auto max-w-6xl px-5 py-14 sm:py-20"><p className="text-sm font-semibold uppercase tracking-wider" style={{color:site.primary_color}}>Services</p><h2 className="text-3xl font-black mt-2 mb-8">What we can help with</h2>{services.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map(s=><div key={s.id} className="rounded-3xl bg-white border p-6 shadow-sm"><div className="text-lg font-bold">{name(s.service,s.variant)}</div><div className="mt-4 text-2xl font-black">{price(s.price_cents)||"Ask for price"}</div><div className="mt-2 text-sm text-slate-500">Contact us to arrange your clean.</div></div>)}</div>:<div className="rounded-3xl bg-white border p-7 text-slate-600">Services and pricing will appear here once published.</div>}</section>}
{site.show_about&&<section className="bg-white border-y"><div className="mx-auto max-w-6xl px-5 py-14 sm:py-20 grid gap-8 lg:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-wider" style={{color:site.primary_color}}>About</p><h2 className="text-3xl font-black mt-2">A local business you can contact directly</h2><p className="mt-5 text-slate-600 leading-7">{intro}</p></div>{site.show_contact&&<div className="rounded-3xl bg-slate-50 border p-7 space-y-4">{cleaner.phone&&<a href={`tel:${cleaner.phone}`} className="block"><div className="text-xs uppercase text-slate-500">Phone</div><div className="font-bold mt-1">{cleaner.phone}</div></a>}{cleaner.contact_email&&<a href={`mailto:${cleaner.contact_email}`} className="block"><div className="text-xs uppercase text-slate-500">Email</div><div className="font-bold mt-1 break-all">{cleaner.contact_email}</div></a>}{cleaner.website&&<a href={website(cleaner.website)} target="_blank" rel="noreferrer" className="block"><div className="text-xs uppercase text-slate-500">Website</div><div className="font-bold mt-1 break-all">{cleaner.website}</div></a>}</div>}</div></section>}</main><footer className="text-white/60" style={{background:site.primary_color}}><div className="mx-auto max-w-6xl px-5 py-8 flex justify-between text-sm"><div>© {new Date().getFullYear()} {cleaner.business_name}</div><Link to="/" className="hover:text-white">Powered by Klean.ly</Link></div></footer></div>}
