import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { supabase } from "../lib/supabase";

type Cleaner={id:string;slug:string;business_name:string|null;logo_url:string|null;address:string|null;phone:string|null;whatsapp:string|null;website:string|null;about:string|null;contact_email:string|null};
type Service={id:string;service:string;variant:string|null;price_cents:number|null};
type Gallery={id:string;image_url:string;caption:string|null};
type Site={headline:string|null;description:string|null;hero_url:string|null;primary_color:string;accent_color:string;show_services:boolean;show_about:boolean;show_contact:boolean;show_gallery:boolean;is_published:boolean};
type Props={forcedSlug?:string;customDomain?:boolean};
const serviceName=(s:string,v:string|null)=>{const n=s.replace(/_/g," ").replace(/\b\w/g,l=>l.toUpperCase());return v?`${n} · ${v}`:n};
const price=(p:number|null)=>p==null?null:new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(p/100);
const website=(v:string)=>/^https?:\/\//i.test(v)?v:`https://${v}`;
function meta(selector:string,attrs:Record<string,string>,content:string){let el=document.head.querySelector<HTMLMetaElement>(selector);if(!el){el=document.createElement("meta");Object.entries(attrs).forEach(([k,v])=>el?.setAttribute(k,v));document.head.appendChild(el)}el.setAttribute("content",content)}

export default function PublicCleanerSite({forcedSlug,customDomain=false}:Props={}){
 const params=useParams<{slug:string}>();const slug=forcedSlug||params.slug;const [cleaner,setCleaner]=useState<Cleaner|null>(null);const [site,setSite]=useState<Site|null>(null);const [services,setServices]=useState<Service[]>([]);const [gallery,setGallery]=useState<Gallery[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
 useEffect(()=>{let cancelled=false;(async()=>{if(!slug){setLoading(false);return}setLoading(true);setError(null);const {data:c,error:ce}=await supabase.from("cleaners").select("id,slug,business_name,logo_url,address,phone,whatsapp,website,about,contact_email").eq("slug",slug).eq("is_published",true).eq("is_active",true).maybeSingle();if(cancelled)return;if(ce){setError(ce.message);setLoading(false);return}if(!c){setCleaner(null);setSite(null);setLoading(false);return}const cd=c as Cleaner;setCleaner(cd);const {data:s,error:se}=await supabase.from("cleaner_sites").select("headline,description,hero_url,primary_color,accent_color,show_services,show_about,show_contact,show_gallery,is_published").eq("cleaner_id",cd.id).eq("is_published",true).maybeSingle();if(cancelled)return;if(se){setError(se.message);setLoading(false);return}if(!s){setSite(null);setLoading(false);return}const sd=s as Site;setSite(sd);const jobs:PromiseLike<unknown>[]=[];if(sd.show_services)jobs.push(supabase.from("service_offerings").select("id,service,variant,price_cents").eq("cleaner_id",cd.id).eq("is_active",true).order("service").then(({data,error})=>{if(error)throw error;setServices((data??[]) as Service[])}));else setServices([]);if(sd.show_gallery)jobs.push(supabase.from("cleaner_gallery").select("id,image_url,caption").eq("cleaner_id",cd.id).order("sort_order").order("created_at").then(({data,error})=>{if(error)throw error;setGallery((data??[]) as Gallery[])}));else setGallery([]);try{await Promise.all(jobs)}catch(e){if(!cancelled)setError(e instanceof Error?e.message:"Could not load website.")}if(!cancelled)setLoading(false)})();return()=>{cancelled=true}},[slug]);
 useEffect(()=>{if(!cleaner||!site)return;const old=document.title;const name=cleaner.business_name||"Local cleaner";const desc=site.description||cleaner.about||`${name} provides professional local cleaning services.`;const canonical=customDomain?`${window.location.origin}${window.location.pathname||"/"}`:`${window.location.origin}/cleaner/${cleaner.slug}`;document.title=`${name} | Local Cleaning Services`;meta('meta[name="description"]',{name:"description"},desc.slice(0,160));meta('meta[property="og:title"]',{property:"og:title"},document.title);meta('meta[property="og:description"]',{property:"og:description"},desc.slice(0,200));meta('meta[property="og:type"]',{property:"og:type"},"website");meta('meta[property="og:url"]',{property:"og:url"},canonical);if(site.hero_url||cleaner.logo_url)meta('meta[property="og:image"]',{property:"og:image"},site.hero_url||cleaner.logo_url||"");let link=document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!link){link=document.createElement("link");link.rel="canonical";document.head.appendChild(link)}link.href=canonical;const script=document.createElement("script");script.type="application/ld+json";script.text=JSON.stringify({"@context":"https://schema.org","@type":"LocalBusiness",name,url:canonical,description:desc,telephone:cleaner.phone||cleaner.whatsapp||undefined,email:cleaner.contact_email||undefined,image:site.hero_url||cleaner.logo_url||undefined,address:cleaner.address||undefined,makesOffer:services.map(s=>({"@type":"Offer",name:serviceName(s.service,s.variant),priceCurrency:"GBP",price:s.price_cents==null?undefined:(s.price_cents/100).toFixed(2)}))});document.head.appendChild(script);return()=>{document.title=old;script.remove()}},[cleaner,site,services,customDomain]);
 if(loading)return <div className="min-h-screen grid place-items-center bg-slate-50">Loading…</div>;if(error)return <div className="min-h-screen grid place-items-center bg-slate-50 px-6"><div className="max-w-lg text-center"><h1 className="text-2xl font-bold mb-2">We couldn't load this cleaner</h1><p className="text-slate-600">{error}</p></div></div>;if(!cleaner||!site)return <div className="min-h-screen grid place-items-center bg-slate-50 px-6"><div className="max-w-lg text-center"><h1 className="text-3xl font-bold mb-3">Cleaner website unavailable</h1><p className="text-slate-600 mb-6">That business page isn't public right now.</p>{!customDomain&&<Link to="/" className="inline-flex rounded-full bg-black px-5 py-3 text-white font-semibold">Back to Klean.ly</Link>}</div></div>;
 const wa=cleaner.whatsapp?.replace(/\D/g,"");const call=cleaner.phone||cleaner.whatsapp;const intro=site.description||cleaner.about||"Professional local cleaning with simple, direct booking and friendly service.";
 return <div className="min-h-screen bg-slate-50 text-slate-950"><header className="bg-white border-b"><div className="mx-auto max-w-6xl px-5 py-5 flex items-center justify-between gap-4"><div className="flex items-center gap-3 min-w-0">{cleaner.logo_url?<img src={cleaner.logo_url} alt={`${cleaner.business_name??"Cleaner"} logo`} className="h-12 w-12 rounded-2xl object-contain border bg-white"/>:<div className="h-12 w-12 rounded-2xl text-white grid place-items-center font-bold text-xl" style={{backgroundColor:site.primary_color}}>{(cleaner.business_name??"K")[0].toUpperCase()}</div>}<div><div className="font-bold">{cleaner.business_name}</div><div className="text-sm text-slate-500">Local cleaning services</div></div></div>{!customDomain&&<span className="text-xs sm:text-sm text-slate-500">Powered by Klean.ly</span>}</div></header><main>
 <section className="text-white bg-cover bg-center" style={{backgroundColor:site.primary_color,backgroundImage:site.hero_url?`linear-gradient(rgba(0,0,0,.55),rgba(0,0,0,.55)),url(${site.hero_url})`:undefined}}><div className="mx-auto max-w-6xl px-5 py-16 sm:py-24 grid gap-10 lg:grid-cols-[1.3fr_.7fr] lg:items-center"><div><p className="uppercase tracking-[.22em] text-xs font-semibold mb-4" style={{color:site.accent_color}}>Trusted local cleaner</p><h1 className="text-4xl sm:text-6xl font-black tracking-tight leading-tight">{site.headline||cleaner.business_name}</h1><p className="mt-6 text-lg sm:text-xl text-white/80 max-w-2xl">{intro}</p>{site.show_contact&&<div className="mt-8 flex flex-wrap gap-3">{wa&&<a href={`https://wa.me/${wa}`} className="rounded-full px-6 py-3 font-bold" style={{backgroundColor:site.accent_color,color:site.primary_color}}>Book on WhatsApp</a>}{call&&<a href={`tel:${call}`} className="rounded-full border border-white/30 px-6 py-3 font-semibold">Call now</a>}</div>}</div><div className="rounded-3xl bg-white/10 border border-white/10 p-6"><div className="text-sm text-white/70">Serving customers around</div><div className="mt-2 text-2xl font-bold">{cleaner.address||"your local area"}</div></div></div></section>
 {site.show_services&&<section className="mx-auto max-w-6xl px-5 py-14 sm:py-20"><p className="text-sm font-semibold uppercase tracking-wider" style={{color:site.primary_color}}>Services</p><h2 className="text-3xl font-black mt-2 mb-8">What we can help with</h2>{services.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map(s=><div key={s.id} className="rounded-3xl bg-white border p-6 shadow-sm"><div className="text-lg font-bold">{serviceName(s.service,s.variant)}</div><div className="mt-4 text-2xl font-black">{price(s.price_cents)||"Ask for price"}</div><div className="mt-2 text-sm text-slate-500">Contact us to arrange your clean.</div></div>)}</div>:<div className="rounded-3xl bg-white border p-7 text-slate-600">Services and pricing will appear here once published.</div>}</section>}
 {site.show_gallery&&gallery.length>0&&<section className="bg-white border-y"><div className="mx-auto max-w-6xl px-5 py-14 sm:py-20"><p className="text-sm font-semibold uppercase tracking-wider" style={{color:site.primary_color}}>Our work</p><h2 className="text-3xl font-black mt-2 mb-8">Recent cleaning</h2><div className="grid grid-cols-2 md:grid-cols-3 gap-3 sm:gap-5">{gallery.map(g=><figure key={g.id} className="overflow-hidden rounded-3xl bg-slate-100 border"><img src={g.image_url} alt={g.caption||`${cleaner.business_name||"Cleaner"} work`} loading="lazy" className="aspect-square h-full w-full object-cover"/>{g.caption&&<figcaption className="p-3 text-sm text-slate-600">{g.caption}</figcaption>}</figure>)}</div></div></section>}
 {site.show_about&&<section className="bg-white"><div className="mx-auto max-w-6xl px-5 py-14 sm:py-20 grid gap-8 lg:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-wider" style={{color:site.primary_color}}>About</p><h2 className="text-3xl font-black mt-2">A local business you can contact directly</h2><p className="mt-5 text-slate-600 leading-7">{intro}</p></div>{site.show_contact&&<div className="rounded-3xl bg-slate-50 border p-7 space-y-4">{cleaner.phone&&<a href={`tel:${cleaner.phone}`} className="block"><div className="text-xs uppercase text-slate-500">Phone</div><div className="font-bold mt-1">{cleaner.phone}</div></a>}{cleaner.contact_email&&<a href={`mailto:${cleaner.contact_email}`} className="block"><div className="text-xs uppercase text-slate-500">Email</div><div className="font-bold mt-1 break-all">{cleaner.contact_email}</div></a>}{cleaner.website&&<a href={website(cleaner.website)} target="_blank" rel="noreferrer" className="block"><div className="text-xs uppercase text-slate-500">Website</div><div className="font-bold mt-1 break-all">{cleaner.website}</div></a>}</div>}</div></section>}
 </main><footer className="text-white/60" style={{backgroundColor:site.primary_color}}><div className="mx-auto max-w-6xl px-5 py-8 flex flex-col sm:flex-row gap-2 sm:items-center sm:justify-between text-sm"><div>© {new Date().getFullYear()} {cleaner.business_name}</div>{!customDomain&&<Link to="/" className="hover:text-white">Powered by Klean.ly</Link>}</div></footer></div>;
}
