import { useEffect, useState, type ChangeEvent } from "react";
import { supabase } from "../lib/supabase";
type GalleryItem={id:string;image_url:string;caption:string|null;sort_order:number};type Props={cleanerId:string};
const errorMessage=(e:unknown,f:string)=>e instanceof Error?e.message:f;
export default function WebsiteGalleryManager({cleanerId}:Props){
 const [items,setItems]=useState<GalleryItem[]>([]),[uploading,setUploading]=useState(false),[message,setMessage]=useState<string|null>(null);
 async function load(){const {data,error}=await supabase.from("cleaner_gallery").select("id,image_url,caption,sort_order").eq("cleaner_id",cleanerId).order("sort_order").order("created_at");if(error)throw error;setItems((data??[]) as GalleryItem[])}
 useEffect(()=>{load().catch((e:unknown)=>setMessage(errorMessage(e,"Could not load gallery.")))},[cleanerId]);
 async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;if(items.length>=24){setMessage("You can add up to 24 gallery photos.");return}if(!["image/jpeg","image/png","image/webp","image/gif"].includes(file.type)){setMessage("Please choose a JPG, PNG, WebP or GIF image.");return}if(file.size>8*1024*1024){setMessage("Images must be smaller than 8 MB.");return}setUploading(true);setMessage(null);try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Please sign in again.");const ext=file.name.split(".").pop()?.toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg";const path=`${user.id}/${cleanerId}/${crypto.randomUUID()}.${ext}`;const {error:ue}=await supabase.storage.from("cleaner-site-images").upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(ue)throw ue;const {data:p}=supabase.storage.from("cleaner-site-images").getPublicUrl(path);const {error:ie}=await supabase.from("cleaner_gallery").insert({cleaner_id:cleanerId,image_url:p.publicUrl,sort_order:items.length});if(ie){await supabase.storage.from("cleaner-site-images").remove([path]);throw ie}await load();setMessage("Photo added to your website gallery.")}catch(e:unknown){setMessage(errorMessage(e,"Could not upload photo."))}finally{setUploading(false)}}
 async function saveCaption(item:GalleryItem,caption:string){setItems(v=>v.map(x=>x.id===item.id?{...x,caption}:x));const {error}=await supabase.from("cleaner_gallery").update({caption:caption.trim()||null}).eq("id",item.id).eq("cleaner_id",cleanerId);if(error)setMessage(error.message)}
 async function remove(item:GalleryItem){setMessage(null);try{const {error}=await supabase.from("cleaner_gallery").delete().eq("id",item.id).eq("cleaner_id",cleanerId);if(error)throw error;const marker="/cleaner-site-images/",index=item.image_url.indexOf(marker);if(index>=0)await supabase.storage.from("cleaner-site-images").remove([decodeURIComponent(item.image_url.slice(index+marker.length))]);await load()}catch(e:unknown){setMessage(errorMessage(e,"Could not remove photo."))}}
 return <section className="card"><div className="card-pad space-y-4"><div className="flex items-start justify-between gap-4 flex-wrap"><div><h2 className="text-lg font-semibold">Photo gallery</h2><p className="muted text-sm">Add before/after photos or examples of your work. Up to 24 images, 8 MB each.</p></div><label className={`btn btn-primary cursor-pointer ${uploading||items.length>=24?"opacity-60 pointer-events-none":""}`}>{uploading?"Uploading…":"Add photo"}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={upload} className="hidden" disabled={uploading||items.length>=24}/></label></div>{message&&<div className="rounded-xl border bg-white px-4 py-3 text-sm">{message}</div>}{items.length===0?<div className="rounded-xl border border-dashed p-5 text-sm text-gray-600">No gallery photos yet.</div>:<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{items.map(item=><div key={item.id} className="rounded-2xl border bg-white overflow-hidden"><img src={item.image_url} alt={item.caption||"Cleaning work"} className="aspect-square w-full object-cover"/><div className="p-3 space-y-2"><input value={item.caption||""} maxLength={120} onChange={e=>setItems(v=>v.map(x=>x.id===item.id?{...x,caption:e.target.value}:x))} onBlur={e=>saveCaption(item,e.target.value)} placeholder="Caption (optional)" className="w-full rounded-lg border px-3 py-2 text-sm"/><button type="button" onClick={()=>remove(item)} className="text-xs underline text-red-700">Remove photo</button></div></div>)}</div>}</div></section>;
}
